help_desk_homepage:
    path:     /hello/{name}
    defaults: { _controller: HelpDeskBundle:Default:index }
    
HelpDeskBundle_chamadas:
    resource: "@HelpDeskBundle/Resources/config/routing/chamadas.yml"
    prefix:   /chamadas

HelpDeskBundle_chamadacategoria:
    resource: "@HelpDeskBundle/Resources/config/routing/chamadacategoria.yml"
    prefix:   /chamadacategoria

HelpDeskBundle_chamadalocal:
    resource: "@HelpDeskBundle/Resources/config/routing/chamadalocal.yml"
    prefix:   /chamadalocal
    
HelpDeskBundle_chamadastatus:
    resource: "@HelpDeskBundle/Resources/config/routing/chamadastatus.yml"
    prefix:   /chamadastatus

HelpDeskBundle_chamadanivel:
    resource: "@HelpDeskBundle/Resources/config/routing/chamadanivel.yml"
    prefix:   /chamadanivel
    
HelpDeskBundle_relatorios:
    resource: "@HelpDeskBundle/Resources/config/routing/relatorios.yml"
    prefix:   /relatorios

HelpDeskBundle_usuarioclasse:
    resource: "@HelpDeskBundle/Resources/config/routing/usuarioclasse.yml"
    prefix:   /usuarioclasse
    
HelpDeskBundle_usuario:
    resource: "@HelpDeskBundle/Resources/config/routing/usuario.yml"
    prefix:   /usuario


login:
    path:     /
    defaults: { _controller: HelpDeskBundle:Login:login }

login_check:
    path:     /login_check
    defaults: { _controller: HelpDeskBundle:Login:login_check }

cliente_home:
    path:     /helpdesk/{userId}/home/
    defaults: { _controller: HelpDeskBundle:Cliente:home }

abrir_chamada:
    path:     /helpdesk/{userId}/abrirChamada/
    defaults: { _controller: HelpDeskBundle:Cliente:abrirChamada }
    
minhas_chamadas:
    path:     /helpdesk/{userId}/minhasChamadas
    defaults: { _controller: HelpDeskBundle:Cliente:minhasChamadas }

todas_chamadas:
    path:     /helpdesk/{userId}/todasChamadas
    defaults: { _controller: HelpDeskBundle:Cliente:todasChamadas }
    
busca:
    path:     /helpdesk/{userId}/todasChamadas/busca
    defaults: { _controller: HelpDeskBundle:BuscaChamados:busca }

todas_chamadas_admin:
    path:     /helpdesk/{userId}/todasChamadasAdmin
    defaults: { _controller: HelpDeskBundle:Cliente:todasChamadasAdmin }    
    
admin_home:
    path:     /helpdesk/{userId}/homeAdmin/
    defaults: { _controller: HelpDeskBundle:Cliente:homeAdmin }    
    
sem_prioridade:
    path:     /helpdesk/{userId}/chamadas/admin/semPrioridade/
    defaults: { _controller: HelpDeskBundle:Cliente:semPrioridade }
    
chamadas_em_aberto:
    path:     /helpdesk/{userId}/chamadas/admin/emAberto
    defaults: { _controller: HelpDeskBundle:Cliente:emAberto }

chamadas_em_andamento:
    path:     /helpdesk/{userId}/chamadas/admin/emAndamento
    defaults: { _controller: HelpDeskBundle:Cliente:emAndamento }
    
chamadas_finalizadas:
    path:     /helpdesk/{userId}/chamadas/admin/finalizadas
    defaults: { _controller: HelpDeskBundle:Cliente:finalizadas }