parameters:
#    help_desk.example.class: Icea\CEA478\HelpDeskBundle\Example

services:
#    help_desk.example:
#        class: %help_desk.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
