Icea\CEA478\HelpDeskBundle\Entity\ChamadaLocal:
    type: entity
    table: chamada_local
    uniqueConstraints:
        descricao_UNIQUE:
            columns:
                - descricao
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descricao:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
